name: Hello, World!
on: push

jobs:
  build:
    name: Greating
    runs-on: ubuntu-latest
    steps:
      - run: docker --version
      - uses: docker://alpine:3.11
        with:
          entrypoint: /bin/echo
          args: Hello, World!
